

-- Abstract model elements
CREATE TABLE MODEL_ELEMENT (
    UUID CHAR(36) NOT NULL,
    SUMMARY VARCHAR(256) NULL
);

ALTER TABLE MODEL_ELEMENT ADD CONSTRAINT PK_MODEL_ELEMENT PRIMARY KEY (UUID);


-- Container elements
CREATE TABLE CONTAINER_ELEMENT (
    UUID CHAR(36) NOT NULL
);

ALTER TABLE CONTAINER_ELEMENT ADD CONSTRAINT PK_CONTAINER_ELEMENT PRIMARY KEY (UUID);

ALTER TABLE CONTAINER_ELEMENT ADD CONSTRAINT FK_CONTAINER_ELEMENT__MODEL_ELEMENT
  FOREIGN KEY (UUID) REFERENCES MODEL_ELEMENT(UUID) ON DELETE CASCADE;


-- Named model elements
CREATE TABLE NAMED_ELEMENT (
    UUID CHAR(36) NOT NULL,
    NAME VARCHAR(128) NOT NULL
);

ALTER TABLE NAMED_ELEMENT ADD CONSTRAINT PK_NAMED_ELEMENT PRIMARY KEY (UUID);

ALTER TABLE NAMED_ELEMENT ADD CONSTRAINT FK_NAMED_ELEMENT__MODEL_ELEMENT
  FOREIGN KEY (UUID) REFERENCES MODEL_ELEMENT(UUID) ON DELETE CASCADE;


-- Named container elements
CREATE TABLE NAMED_CONTAINER_ELEMENT (
    UUID CHAR(36) NOT NULL
);

ALTER TABLE NAMED_CONTAINER_ELEMENT ADD CONSTRAINT PK_NAMED_CONTAINER_ELEMENT PRIMARY KEY (UUID);

ALTER TABLE NAMED_CONTAINER_ELEMENT ADD CONSTRAINT FK_NAMED_CONTAINER_ELEMENT__NAMED_ELEMENT
  FOREIGN KEY (UUID) REFERENCES NAMED_ELEMENT(UUID) ON DELETE CASCADE;

ALTER TABLE NAMED_CONTAINER_ELEMENT ADD CONSTRAINT FK_NAMED_CONTAINER_ELEMENT__CONTAINER_ELEMENT
  FOREIGN KEY (UUID) REFERENCES CONTAINER_ELEMENT(UUID) ON DELETE CASCADE;


-- Namespaces
CREATE TABLE NAMESPACE (
    UUID CHAR(36) NOT NULL
);

ALTER TABLE NAMESPACE ADD CONSTRAINT PK_NAMESPACE PRIMARY KEY (UUID);

ALTER TABLE NAMESPACE ADD CONSTRAINT FK_NAMESPACE__NAMED_CONTAINER_ELEMENT
  FOREIGN KEY (UUID) REFERENCES NAMED_CONTAINER_ELEMENT(UUID) ON DELETE CASCADE;

CREATE VIEW V_NAMESPACE AS
SELECT MODEL_ELEMENT.UUID UUID,
       NAMED_ELEMENT.NAME NAME,
       MODEL_ELEMENT.SUMMARY SUMMARY
  FROM MODEL_ELEMENT
  INNER JOIN CONTAINER_ELEMENT ON CONTAINER_ELEMENT.UUID = MODEL_ELEMENT.UUID
  INNER JOIN NAMED_ELEMENT ON NAMED_ELEMENT.UUID = MODEL_ELEMENT.UUID
  INNER JOIN NAMED_CONTAINER_ELEMENT ON NAMED_CONTAINER_ELEMENT.UUID = NAMED_ELEMENT.UUID
  INNER JOIN NAMESPACE ON NAMESPACE.UUID = NAMED_CONTAINER_ELEMENT.UUID;
