
----------------------
-- Abstract Actions --
----------------------

-- Table
CREATE TABLE ACTION (
    ID UUID NOT NULL,
    TYPE VARCHAR(128) NOT NULL  -- TBD: foreign key to reference table or else Java enum
);

-- Primary key
ALTER TABLE ACTION ADD CONSTRAINT PK_ACTION
    PRIMARY KEY (ID);


------------------------------
-- Create Namespace Actions --
------------------------------

-- Table
CREATE TABLE CREATE_NAMESPACE_ACTION (
    ID UUID NOT NULL,
    NEW_NAMESPACE_ID UUID NOT NULL
);

-- Primary key
ALTER TABLE CREATE_NAMESPACE_ACTION ADD CONSTRAINT PK_CREATE_NAMESPACE_ACTION
    PRIMARY KEY (ID);

-- Inheritance
ALTER TABLE CREATE_NAMESPACE_ACTION ADD CONSTRAINT PFK_CREATE_NAMESPACE_ACTION__ACTION
    FOREIGN KEY (ID) REFERENCES ACTION(ID) ON DELETE CASCADE;

-- Foreign keys
ALTER TABLE CREATE_NAMESPACE_ACTION ADD CONSTRAINT FK_CREATE_NAMESPACE_ACTION__NEW_NAMESPACE
    FOREIGN KEY (NEW_NAMESPACE_ID) REFERENCES NAMESPACE(ID) ON DELETE CASCADE;

