
-----------------------
-- Abstract entities --
-----------------------

-- Table
CREATE TABLE ENTITY (
    ID UUID NOT NULL,
    TYPE VARCHAR(128) NOT NULL  -- TBD: foreign key to reference table or else Java enum
);

-- Primary key
ALTER TABLE ENTITY ADD CONSTRAINT PK_ENTITY PRIMARY KEY (ID);


--------------------
-- Named entities --
--------------------

-- Table
CREATE TABLE NAMED_ENTITY (
    ID UUID NOT NULL
);

-- Primary key
ALTER TABLE NAMED_ENTITY ADD CONSTRAINT PK_NAMED_ENTITY PRIMARY KEY (ID);

-- Inheritance
ALTER TABLE NAMED_ENTITY ADD CONSTRAINT PFK_NAMED_ENTITY__ENTITY
  FOREIGN KEY (ID) REFERENCES ENTITY(ID) ON DELETE CASCADE;


-------------------------
-- Abstract namespaces --
-------------------------

-- Table
CREATE TABLE ABSTRACT_NAMESPACE (
    ID UUID NOT NULL
);

-- Primary key
ALTER TABLE ABSTRACT_NAMESPACE ADD CONSTRAINT PK_ABSTRACT_NAMESPACE PRIMARY KEY (ID);

-- Inheritance
ALTER TABLE ABSTRACT_NAMESPACE ADD CONSTRAINT PFK_ABSTRACT_NAMESPACE__NAMED_ENTITY
  FOREIGN KEY (ID) REFERENCES NAMED_ENTITY(ID) ON DELETE CASCADE;


----------------
-- Namespaces --
----------------

-- Table
CREATE TABLE NAMESPACE (
    ID UUID NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    SUMMARY VARCHAR(256) NULL,
    DESTROYED BOOLEAN NOT NULL DEFAULT FALSE,
);

-- Primary key
ALTER TABLE NAMESPACE ADD CONSTRAINT PK_NAMESPACE PRIMARY KEY (ID);

-- Inheritance
ALTER TABLE NAMESPACE ADD CONSTRAINT PFK_NAMESPACE__ABSTRACT_NAMESPACE
  FOREIGN KEY (ID) REFERENCES ABSTRACT_NAMESPACE(ID) ON DELETE CASCADE;

-- Indexes
CREATE INDEX IDX_NAMESPACE__NAME ON NAMESPACE(NAME);

-- View
CREATE VIEW V_NAMESPACE AS
SELECT ID,
       NAME,
       SUMMARY
  FROM NAMESPACE
 WHERE DESTROYED = FALSE;


--------------------
-- Root namespace --
--------------------

-- Table
CREATE TABLE ROOT_NAMESPACE (
    ID UUID NOT NULL,
    SUMMARY VARCHAR(256) NULL,
    SINGLE_ROW_ENFORCEMENT BOOLEAN NOT NULL DEFAULT TRUE
);

-- Primary key
ALTER TABLE ROOT_NAMESPACE ADD CONSTRAINT PK_ROOT_NAMESPACE PRIMARY KEY (ID);

-- Inheritance
ALTER TABLE ROOT_NAMESPACE ADD CONSTRAINT PFK_ROOT_NAMESPACE__ABSTRACT_NAMESPACE
  FOREIGN KEY (ID) REFERENCES ABSTRACT_NAMESPACE(ID) ON DELETE CASCADE;

-- Singleton enforcement
ALTER TABLE ROOT_NAMESPACE ADD CONSTRAINT UQ_ROOT_NAMESPACE__SINGLE_ROW_ENFORCEMENT UNIQUE (SINGLE_ROW_ENFORCEMENT);
ALTER TABLE ROOT_NAMESPACE ADD CONSTRAINT CHK_ROOT_NAMESPACE__SINGLE_ROW CHECK (SINGLE_ROW_ENFORCEMENT = TRUE);

-- View
CREATE VIEW V_ROOT_NAMESPACE AS
SELECT ID,
       '$',
       SUMMARY
  FROM ROOT_NAMESPACE;

-- Singleton instance
INSERT INTO ENTITY (ID, TYPE)
     VALUES ('bf6d4bfc-b169-4919-8712-05e54484921e', 'RootNamespace');
INSERT INTO NAMED_ENTITY (ID)
     VALUES ('bf6d4bfc-b169-4919-8712-05e54484921e');
INSERT INTO ABSTRACT_NAMESPACE (ID)
     VALUES ('bf6d4bfc-b169-4919-8712-05e54484921e');
INSERT INTO ROOT_NAMESPACE (ID, SUMMARY)
     VALUES ('bf6d4bfc-b169-4919-8712-05e54484921e', '(Top level namespace)');


